name: dinov2
channels:
  - defaults
  - pytorch
  - nvidia
  - xformers
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch=2.0.0
  - pytorch::pytorch-cuda=11.7.0
  - pytorch::torchvision=0.15.0
  - omegaconf
  - tqdm
  - natsort
  - wandb
  - einops
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - xformers::xformers
  - pip
  - pip:
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11
