dino:
  head_bottleneck_dim: 384
ibot:
  separate_head: true
train:
  batch_size_per_gpu: 128
  dataset_path: PathologyFoundation:root=/root/data
  centering: sinkhorn_knopp
  num_workers: 8
tune:
  tune_every:
  query_dataset_path: KNN:root=/root/data:split=query
  test_dataset_path: KNN:root=/root/data:split=test
  early_stopping:
    enable: false
  knn:
    batch_size: 64
student:
  arch: vit_small
  patch_size: 14
  num_register_tokens: 0
  pretrained_weights: # 'checkpoints/dinov2_vits14_pretrain.pth'
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 100
  weight_decay_end: 0.2
  base_lr: 2.0e-03 # learning rate for a batch size of 1024, will get scaled in apply_scaling_rules_to_cfg
  warmup_epochs: 16
  layerwise_decay: 1.0
crops:
  local_crops_size: 98
wandb:
  enable: false
  project: 'dinov2'
  username: 'vlfm'
  exp_name: 'profiling'
  tags: ['${wandb.exp_name}', 'patch', '${student.arch}']
  dir: '/home/user'
  group:
  resume_id:
